use std::collections::{BTreeMap, BTreeSet};

use crate::diagnostic::Span;
use crate::syntax::ast::{
    BinaryOp, Block, CallArg, Callee, ConstDecl, DataEffect, EffectDecl, Expr, FieldDecl,
    FunctionDecl, Item, MatchPattern, Param, Program, Stmt, SumTypeDecl, TypeAliasDecl, TypeDecl,
    TypeKind, TypeRef,
};

use super::helpers::*;
use super::source_map::{generated_span_at_end, push_source_marker};
use super::types::{LoweredRust, RustSourceMapEntry};

pub(super) struct RustLowerer<'a> {
    program: &'a Program,
    type_kinds: BTreeMap<String, TypeKind>,
    protocol_names: BTreeSet<String>,
    native_boundary_callees: BTreeSet<String>,
    async_native_boundary_callees: BTreeSet<String>,
    native_bindings: BTreeMap<String, String>,
    function_return_types: BTreeMap<String, TypeRef>,
    retained_params_by_callee: BTreeMap<String, BTreeSet<String>>,
    param_effects: BTreeMap<String, DataEffect>,
    value_types: BTreeMap<String, TypeRef>,
    managed_bindings: BTreeSet<String>,
    read_view_bindings: BTreeSet<String>,
    current_retained_params: BTreeSet<String>,
    mutated_bindings: BTreeSet<String>,
    drop_field_names: BTreeSet<String>,
    current_return_type: Option<TypeRef>,
    current_async_executor: Option<String>,
    source_map: Vec<RustSourceMapEntry>,
}

impl<'a> RustLowerer<'a> {
    pub(super) fn new(program: &'a Program, native_bindings: BTreeMap<String, String>) -> Self {
        let type_kinds = program
            .items
            .iter()
            .filter_map(|item| match item {
                Item::Type(ty) => Some((ty.name.clone(), ty.kind)),
                Item::SumType(_) => None, // sum types don't contribute to type_kinds map
                Item::Function(_) | Item::TypeAlias(_) | Item::Const(_) | Item::Module(_) | Item::Use(_) => None,
            })
            .collect();
        let native_boundary_callees = collect_native_boundary_callees(program);
        let async_native_boundary_callees = collect_async_native_boundary_callees(program);
        let protocol_names = program
            .protocols
            .iter()
            .map(|protocol| protocol.name.clone())
            .collect();
        let function_return_types = collect_function_return_types(program);
        let retained_params_by_callee = collect_function_retained_params(program);

        Self {
            program,
            type_kinds,
            protocol_names,
            native_boundary_callees,
            async_native_boundary_callees,
            native_bindings,
            function_return_types,
            retained_params_by_callee,
            param_effects: BTreeMap::new(),
            value_types: BTreeMap::new(),
            managed_bindings: BTreeSet::new(),
            read_view_bindings: BTreeSet::new(),
            current_retained_params: BTreeSet::new(),
            mutated_bindings: BTreeSet::new(),
            drop_field_names: BTreeSet::new(),
            current_return_type: None,
            current_async_executor: None,
            source_map: Vec::new(),
        }
    }

    pub(super) fn lower(mut self) -> LoweredRust {
        let mut out = String::new();
        out.push_str("// Generated by RSScript. Edit the .rss source instead.\n");
        out.push_str(
            "// Runtime hooks are intentionally explicit while Rust lowering is stabilizing.\n",
        );
        out.push_str("#![allow(dead_code, non_snake_case)]\n");
        let feature_names = lowered_feature_names(&self.program.features);
        if feature_names.is_empty() {
            out.push_str("// RSScript features: <none>\n");
        } else {
            out.push_str(&format!(
                "// RSScript features: {}\n",
                feature_names.join(", ")
            ));
        }
        out.push('\n');

        for item in &self.program.items {
            if let Item::Type(ty) = item {
                self.lower_type_decl(ty, &mut out);
                out.push('\n');
            }
        }
        for item in &self.program.items {
            if let Item::SumType(sum) = item {
                self.lower_sum_type(sum, &mut out);
                out.push('\n');
            }
        }
        // Lower type aliases
        for item in &self.program.items {
            if let Item::TypeAlias(alias) = item {
                self.lower_type_alias(alias, &mut out);
                out.push('\n');
            }
        }
        // Lower constants
        for item in &self.program.items {
            if let Item::Const(decl) = item {
                self.lower_const_decl(decl, &mut out);
                out.push('\n');
            }
        }
        self.lower_protocol_traits(&mut out);
        for item in &self.program.items {
            match item {
                Item::Type(_) | Item::Module(_) | Item::Use(_) | Item::SumType(_) | Item::TypeAlias(_) | Item::Const(_) => {}
                Item::Function(function) if !function.body.statements.is_empty() => {
                    self.lower_function(function, &mut out);
                    out.push('\n');
                }
                Item::Function(_) => {}
            }
        }
        self.lower_protocol_impls(&mut out);
        while out.ends_with("\n\n") {
            out.pop();
        }

        LoweredRust {
            rust_source: out,
            source_map: self.source_map,
        }
    }

    fn lower_protocol_traits(&mut self, out: &mut String) {
        for protocol in &self.program.protocols {
            self.record_source_marker(out, 0, "protocol", &protocol.span);
            out.push_str(&format!("pub trait {} {{\n", rust_ident(&protocol.name)));
            for method in protocol_methods(self.program, &protocol.name) {
                out.push_str("    fn ");
                out.push_str(&rust_ident(protocol_method_name(&method.name)));
                out.push('(');
                out.push_str(&self.lower_protocol_trait_params(method));
                out.push(')');
                if let Some(return_ty) = &method.return_ty {
                    out.push_str(" -> ");
                    out.push_str(&self.lower_return_type(return_ty, method.returns_fresh));
                }
                out.push_str(";\n");
            }
            out.push_str("}\n\n");
        }
    }

    fn lower_protocol_trait_params(&self, method: &FunctionDecl) -> String {
        method
            .params
            .iter()
            .map(|param| {
                if param.name == "self" {
                    return match param.effect {
                        Some(DataEffect::Read) => "&self".to_string(),
                        Some(DataEffect::Mut) => "&mut self".to_string(),
                        Some(DataEffect::Take) | None => "self".to_string(),
                    };
                }
                self.lower_param(param)
            })
            .collect::<Vec<_>>()
            .join(", ")
    }

    fn lower_protocol_impls(&mut self, out: &mut String) {
        for protocol_impl in &self.program.protocol_impls {
            out.push_str(&format!(
                "impl {} for {} {{\n",
                rust_ident(&protocol_impl.protocol),
                rust_ident(&protocol_impl.type_name)
            ));
            for mapping in &protocol_impl.mappings {
                let Some(method) =
                    protocol_method(self.program, &protocol_impl.protocol, &mapping.method)
                else {
                    continue;
                };
                out.push_str("    fn ");
                out.push_str(&rust_ident(&mapping.method));
                out.push('(');
                out.push_str(&self.lower_protocol_trait_params(method));
                out.push(')');
                if let Some(return_ty) = &method.return_ty {
                    out.push_str(" -> ");
                    out.push_str(&self.lower_return_type(return_ty, method.returns_fresh));
                }
                out.push_str(" {\n        ");
                if method
                    .return_ty
                    .as_ref()
                    .is_none_or(|return_ty| return_ty.name != "Unit")
                {
                    out.push_str("return ");
                }
                out.push_str(&rust_function_ident(&mapping.target));
                out.push('(');
                out.push_str(
                    &method
                        .params
                        .iter()
                        .map(protocol_impl_forward_arg)
                        .collect::<Vec<_>>()
                        .join(", "),
                );
                out.push_str(");\n");
                out.push_str("    }\n");
            }
            out.push_str("}\n\n");
        }
    }

    fn lower_type_decl(&mut self, ty: &TypeDecl, out: &mut String) {
        self.record_source_marker(out, 0, "type", &ty.span);
        if ty.kind == TypeKind::Resource {
            out.push_str("#[must_use]\n");
        }
        let derive_str = self.compute_derive_attr(&ty.derives, ty.kind == TypeKind::Resource);
        out.push_str(&derive_str);
        out.push_str(&format!(
            "{}struct {}{} {{\n",
            visibility(true),
            rust_ident(&ty.name),
            lower_generic_params(&ty.type_params)
        ));
        for field in &ty.fields {
            self.lower_field_decl(field, out);
        }
        out.push_str("}\n");

        if ty.kind == TypeKind::Resource {
            out.push_str(&format!(
                "\nimpl{} rsscript_runtime::Resource for {}{} {{}}\n",
                lower_impl_generics(&ty.type_params),
                rust_ident(&ty.name),
                lower_generic_args(&ty.type_params)
            ));
            out.push_str(&format!(
                "\nimpl{} Drop for {}{} {{\n",
                lower_impl_generics(&ty.type_params),
                rust_ident(&ty.name),
                lower_generic_args(&ty.type_params)
            ));
            out.push_str("    fn drop(&mut self) {\n");
            if let Some(drop_body) = &ty.drop_body {
                let previous_drop_field_names = std::mem::take(&mut self.drop_field_names);
                self.drop_field_names = ty.fields.iter().map(|field| field.name.clone()).collect();
                self.lower_block(drop_body, out, 2);
                self.drop_field_names = previous_drop_field_names;
            } else {
                out.push_str("        // RSScript resource has no explicit drop body.\n");
            }
            out.push_str("    }\n");
            out.push_str("}\n");
        }
    }

    fn lower_field_decl(&mut self, field: &FieldDecl, out: &mut String) {
        let rust_ty = self.lower_type_ref(&field.ty, ManagedPosition::Bare);
        self.source_map.push(RustSourceMapEntry {
            kind: "field".to_string(),
            source: field.span.clone(),
            generated: generated_span_at_end(out, "src/lib.rs", "field"),
        });
        if field.is_weak {
            out.push_str(&format!(
                "    pub {}: rsscript_runtime::WeakManaged<{}>,\n",
                rust_ident(&field.name),
                rust_ty
            ));
        } else if field.is_handle
            || matches!(self.type_kinds.get(&field.ty.name), Some(TypeKind::Class))
        {
            out.push_str(&format!(
                "    pub {}: rsscript_runtime::Managed<{}>,\n",
                rust_ident(&field.name),
                rust_ty
            ));
        } else {
            out.push_str(&format!(
                "    pub {}: {},\n",
                rust_ident(&field.name),
                rust_ty
            ));
        }
    }

    fn lower_sum_type(&mut self, sum: &SumTypeDecl, out: &mut String) {
        let derive_str = self.compute_derive_attr(&sum.derives, false);
        out.push_str(&derive_str);
        out.push_str(&format!(
            "{}enum {} {{\n",
            visibility(sum.is_public),
            rust_ident(&sum.name)
        ));
        for variant in &sum.variants {
            if variant.fields.is_empty() {
                out.push_str(&format!("    {},\n", rust_ident(&variant.name)));
            } else {
                out.push_str(&format!("    {} {{\n", rust_ident(&variant.name)));
                for field in &variant.fields {
                    let rust_ty = self.lower_type_ref(&field.ty, ManagedPosition::Bare);
                    out.push_str(&format!(
                        "        {}: {},\n",
                        rust_ident(&field.name),
                        rust_ty
                    ));
                }
                out.push_str("    },\n");
            }
        }
        out.push_str("}\n");
    }

    /// Compute the `#[derive(...)]` attribute string.
    /// If user specified `derives(...)`, use those (always including Debug).
    /// Otherwise use defaults: Debug + Clone for non-resource, Debug only for resource.
    fn compute_derive_attr(&self, user_derives: &[String], is_resource: bool) -> String {
        if user_derives.is_empty() {
            if is_resource {
                return "#[derive(Debug)]\n".to_string();
            } else {
                return "#[derive(Debug, Clone)]\n".to_string();
            }
        }
        let mut rust_derives = Vec::new();
        // Always include Debug
        rust_derives.push("Debug".to_string());
        for d in user_derives {
            match d.as_str() {
                "Debug" => {} // already added
                "Clone" => rust_derives.push("Clone".to_string()),
                "Eq" => {
                    rust_derives.push("PartialEq".to_string());
                    rust_derives.push("Eq".to_string());
                }
                "Hash" => rust_derives.push("Hash".to_string()),
                // JsonEncode/JsonDecode recognized but not lowered without serde
                "JsonEncode" | "JsonDecode" => {}
                _ => {} // unknown derives silently ignored
            }
        }
        format!("#[derive({})]\n", rust_derives.join(", "))
    }

    fn lower_type_alias(&mut self, alias: &TypeAliasDecl, out: &mut String) {
        let vis = visibility(alias.is_public);
        let generics = lower_generic_params(&alias.type_params);
        let target = self.lower_type_ref(&alias.target, ManagedPosition::Bare);
        out.push_str(&format!(
            "{}type {}{} = {};\n",
            vis,
            rust_ident(&alias.name),
            generics,
            target
        ));
    }

    fn lower_const_decl(&mut self, decl: &ConstDecl, out: &mut String) {
        let vis = visibility(decl.is_public);
        let ty_str = if let Some(ty) = &decl.type_annotation {
            let lowered = self.lower_type_ref(ty, ManagedPosition::Bare);
            // Rust `const` cannot hold heap-allocated String; use &'static str
            if lowered == "String" {
                "&'static str".to_string()
            } else {
                lowered
            }
        } else {
            infer_const_type(&decl.value)
        };
        let value_str = lower_const_value(&decl.value);
        out.push_str(&format!(
            "{}const {}: {} = {};\n",
            vis,
            rust_ident(&decl.name).to_uppercase(),
            ty_str,
            value_str
        ));
    }

    fn lower_function(&mut self, function: &FunctionDecl, out: &mut String) {
        let previous_param_effects = std::mem::take(&mut self.param_effects);
        let previous_value_types = std::mem::take(&mut self.value_types);
        let previous_managed_bindings = std::mem::take(&mut self.managed_bindings);
        let previous_read_view_bindings = std::mem::take(&mut self.read_view_bindings);
        let previous_retained_params = std::mem::take(&mut self.current_retained_params);
        let previous_mutated_bindings = std::mem::take(&mut self.mutated_bindings);
        let previous_return_type = self.current_return_type.take();
        let previous_async_executor = self.current_async_executor.take();
        self.param_effects = function
            .params
            .iter()
            .filter_map(|param| param.effect.map(|effect| (param.name.clone(), effect)))
            .collect();
        self.value_types = function
            .params
            .iter()
            .map(|param| (param.name.clone(), param.ty.clone()))
            .collect();
        self.managed_bindings = function
            .params
            .iter()
            .filter(|param| self.is_class_type(&param.ty))
            .map(|param| param.name.clone())
            .collect();
        self.current_retained_params = function
            .effects
            .iter()
            .filter_map(|effect| match effect {
                EffectDecl::Retains(param) => Some(param.clone()),
                EffectDecl::Name(_) => None,
            })
            .collect();
        self.mutated_bindings = collect_mutated_bindings(&function.body);
        self.current_return_type = function.return_ty.clone();
        self.current_async_executor = (function.is_async && block_has_await(&function.body))
            .then(|| "__rsscript_async_executor".to_string());
        self.record_source_marker(out, 0, "function", &function.span);
        let is_public = function.is_public || is_runnable_main(function);
        out.push_str(&format!(
            "{}fn {}{}(",
            visibility(is_public),
            rust_function_ident(&function.name),
            lower_generic_params(&function.type_params)
        ));
        out.push_str(
            &function
                .params
                .iter()
                .map(|param| self.lower_param(param))
                .collect::<Vec<_>>()
                .join(", "),
        );
        out.push(')');
        if let Some(return_ty) = &function.return_ty {
            out.push_str(" -> ");
            out.push_str(&self.lower_return_type(return_ty, function.returns_fresh));
        }
        out.push_str(" {\n");
        if function.effects.iter().any(is_native_boundary) {
            out.push_str(
                "    // RSScript native/unsafe boundary: review before binding implementation.\n",
            );
        }
        if let Some(executor) = &self.current_async_executor {
            out.push_str(&format!(
                "    let mut {executor} = rsscript_runtime::Executor::new();\n"
            ));
        }
        self.lower_block(&function.body, out, 1);
        out.push_str("}\n");
        self.param_effects = previous_param_effects;
        self.value_types = previous_value_types;
        self.managed_bindings = previous_managed_bindings;
        self.read_view_bindings = previous_read_view_bindings;
        self.current_retained_params = previous_retained_params;
        self.mutated_bindings = previous_mutated_bindings;
        self.current_return_type = previous_return_type;
        self.current_async_executor = previous_async_executor;
    }

    fn lower_param(&self, param: &Param) -> String {
        let ty = if param.effect == Some(DataEffect::Read)
            && self.current_retained_params.contains(&param.name)
            && !self.is_class_type(&param.ty)
            && self.type_kinds.contains_key(&param.ty.name)
        {
            format!(
                "rsscript_runtime::Managed<{}>",
                self.lower_type_ref(&param.ty, ManagedPosition::Bare)
            )
        } else {
            self.lower_type_ref(&param.ty, ManagedPosition::Param)
        };
        let rust_ty = match param.effect {
            Some(DataEffect::Read) => format!("&{ty}"),
            Some(DataEffect::Mut) if self.is_class_type(&param.ty) => format!("&{ty}"),
            Some(DataEffect::Mut) => format!("&mut {ty}"),
            Some(DataEffect::Take) | None => ty,
        };
        let name = rust_value_ident(&param.name);
        if param.ty.is_noescape && param.ty.name == "Fn" {
            format!("mut {name}: {rust_ty}")
        } else {
            format!("{name}: {rust_ty}")
        }
    }

    fn lower_return_type(&self, ty: &TypeRef, returns_fresh: bool) -> String {
        let position = if returns_fresh {
            ManagedPosition::FreshReturn
        } else {
            ManagedPosition::Return
        };
        self.lower_type_ref(ty, position)
    }

    fn lower_block(&mut self, block: &Block, out: &mut String, indent: usize) {
        for statement in &block.statements {
            self.lower_stmt(statement, out, indent);
        }
    }

    fn lower_stmt(&mut self, statement: &Stmt, out: &mut String, indent: usize) {
        let pad = "    ".repeat(indent);
        let marker = self.record_source_marker(out, indent, "statement", stmt_span(statement));
        self.record_statement_source_map(statement, &marker.generated);
        match statement {
            Stmt::Let(stmt) => {
                let mutable = if self.mutated_bindings.contains(&stmt.name)
                    || stmt
                        .value
                        .as_ref()
                        .is_some_and(closure_value_mutates_capture)
                {
                    "mut "
                } else {
                    ""
                };
                if let Some(value) = &stmt.value {
                    let lowered = self.lower_expr(value);
                    let inferred_ty = self.infer_expr_type(value);
                    out.push_str(&format!(
                        "{pad}let {mutable}{} = {};\n",
                        rust_ident(&stmt.name),
                        lowered
                    ));
                    if let Some(ty) = inferred_ty {
                        self.value_types.insert(stmt.name.clone(), ty);
                    }
                    if self.expr_lowers_to_managed_handle(value) {
                        self.managed_bindings.insert(stmt.name.clone());
                    } else {
                        self.managed_bindings.remove(&stmt.name);
                    }
                } else {
                    out.push_str(&format!("{pad}let {mutable}{};\n", rust_ident(&stmt.name)));
                    self.managed_bindings.remove(&stmt.name);
                }
            }
            Stmt::Return(stmt) => {
                if let Some(value) = &stmt.value {
                    let lowered = self.lower_return_expr(value);
                    out.push_str(&format!("{pad}return {lowered};\n"));
                } else {
                    out.push_str(&format!("{pad}return;\n"));
                }
            }
            Stmt::With(stmt) => {
                let resource = self.lower_expr(&stmt.resource);
                let resource = if is_resource_pool_borrow_expr(&stmt.resource) {
                    format!("rsscript_runtime::unwrap_runtime({resource})")
                } else if is_file_open_expr(&stmt.resource) {
                    format!("{resource}?")
                } else {
                    resource
                };
                out.push_str(&format!("{pad}{{\n"));
                let inner_pad = "    ".repeat(indent + 1);
                out.push_str(&format!(
                    "{inner_pad}let mut {} = {};\n",
                    rust_ident(&stmt.binding),
                    resource
                ));
                self.lower_block(&stmt.body, out, indent + 1);
                self.record_source_marker(out, indent + 1, "resource_drop", &stmt.span);
                out.push_str(&format!("{pad}}}\n"));
            }
            Stmt::If(stmt) => {
                out.push_str(&format!(
                    "{pad}if {} {{\n",
                    self.lower_expr(&stmt.condition)
                ));
                self.lower_block(&stmt.then_body, out, indent + 1);
                if let Some(else_body) = &stmt.else_body {
                    out.push_str(&format!("{pad}}} else {{\n"));
                    self.lower_block(else_body, out, indent + 1);
                }
                out.push_str(&format!("{pad}}}\n"));
            }
            Stmt::Loop(stmt) => {
                if let Some(condition) = &stmt.condition {
                    out.push_str(&format!("{pad}while {} {{\n", self.lower_expr(condition)));
                } else {
                    out.push_str(&format!("{pad}loop {{\n"));
                }
                self.lower_block(&stmt.body, out, indent + 1);
                out.push_str(&format!("{pad}}}\n"));
            }
            Stmt::For(stmt) => {
                let iterable = self.lower_expr(&stmt.iterable);
                let previous_type = self.value_types.get(&stmt.binding).cloned();
                let previous_managed = self.managed_bindings.contains(&stmt.binding);
                let previous_read_view = self.read_view_bindings.contains(&stmt.binding);
                let item_type = self
                    .infer_expr_type(&stmt.iterable)
                    .as_ref()
                    .and_then(list_element_type_ref);
                if let Some(item_type) = item_type.clone() {
                    if self.is_class_type(&item_type) {
                        self.managed_bindings.insert(stmt.binding.clone());
                    } else {
                        self.managed_bindings.remove(&stmt.binding);
                    }
                    self.value_types.insert(stmt.binding.clone(), item_type);
                }
                let iterator = if item_type.as_ref().is_some_and(is_copy_type_ref) {
                    self.read_view_bindings.remove(&stmt.binding);
                    format!("({iterable}).iter().cloned()")
                } else {
                    self.read_view_bindings.insert(stmt.binding.clone());
                    format!("({iterable}).iter()")
                };
                out.push_str(&format!(
                    "{pad}for {} in {iterator} {{\n",
                    rust_ident(&stmt.binding)
                ));
                self.lower_block(&stmt.body, out, indent + 1);
                out.push_str(&format!("{pad}}}\n"));
                match previous_type {
                    Some(ty) => {
                        self.value_types.insert(stmt.binding.clone(), ty);
                    }
                    None => {
                        self.value_types.remove(&stmt.binding);
                    }
                }
                if previous_managed {
                    self.managed_bindings.insert(stmt.binding.clone());
                } else {
                    self.managed_bindings.remove(&stmt.binding);
                }
                if previous_read_view {
                    self.read_view_bindings.insert(stmt.binding.clone());
                } else {
                    self.read_view_bindings.remove(&stmt.binding);
                }
            }
            Stmt::Match(stmt) => {
                out.push_str(&format!("{pad}match {} {{\n", self.lower_expr(&stmt.value)));
                // Determine if this is a sum type match (qualify variant patterns)
                let sum_type_name = self.find_sum_type_for_match(&stmt.arms);
                for arm in &stmt.arms {
                    let pattern = if let Some(ref sum_name) = sum_type_name {
                        lower_match_pattern_qualified(&arm.pattern, sum_name)
                    } else {
                        lower_match_pattern(&arm.pattern)
                    };
                    out.push_str(&format!(
                        "{}{} => {{\n",
                        "    ".repeat(indent + 1),
                        pattern
                    ));
                    self.lower_block(&arm.body, out, indent + 2);
                    out.push_str(&format!("{}}},\n", "    ".repeat(indent + 1)));
                }
                out.push_str(&format!("{pad}}}\n"));
            }
            Stmt::LetElse(stmt) => {
                let pattern = lower_match_pattern(&stmt.pattern);
                let value = self.lower_expr(&stmt.value);
                out.push_str(&format!("{pad}let {pattern} = {value} else {{\n"));
                self.lower_block(&stmt.else_body, out, indent + 1);
                out.push_str(&format!("{pad}}};\n"));
                if !stmt.binding_name.is_empty() {
                    let binding_type = match &stmt.pattern {
                        MatchPattern::Variant {
                            name,
                            binding: Some(_),
                            ..
                        } => self.infer_expr_type(&stmt.value).and_then(|ty| match name.as_str() {
                            "Some" if ty.name == "Option" => ty.args.first().cloned(),
                            "Ok" if ty.name == "Result" => ty.args.first().cloned(),
                            "Err" if ty.name == "Result" => ty.args.get(1).cloned(),
                            _ => None,
                        }),
                        _ => None,
                    };
                    if let Some(binding_type) = binding_type {
                        if self.is_class_type(&binding_type) {
                            self.managed_bindings.insert(stmt.binding_name.clone());
                        } else {
                            self.managed_bindings.remove(&stmt.binding_name);
                        }
                        self.value_types
                            .insert(stmt.binding_name.clone(), binding_type);
                    }
                    self.read_view_bindings.remove(&stmt.binding_name);
                }
            }
            Stmt::Break(_) => out.push_str(&format!("{pad}break;\n")),
            Stmt::Continue(_) => out.push_str(&format!("{pad}continue;\n")),
            Stmt::Expr(expr) => out.push_str(&format!("{pad}{};\n", self.lower_expr(expr))),
            Stmt::MalformedWith(span)
            | Stmt::MalformedIf(span)
            | Stmt::MalformedLoop(span)
            | Stmt::MalformedFor(span)
            | Stmt::MalformedMatch(span)
            | Stmt::Unknown(span) => unreachable_lowering("statement", span),
        }
    }

    fn record_source_marker(
        &mut self,
        out: &mut String,
        indent: usize,
        kind: &str,
        span: &Span,
    ) -> RustSourceMapEntry {
        let entry = push_source_marker(out, indent, kind, span);
        self.source_map.push(entry.clone());
        entry
    }

    fn record_statement_source_map(&mut self, statement: &Stmt, generated: &Span) {
        match statement {
            Stmt::Let(stmt) => {
                if let Some(value) = &stmt.value {
                    self.record_expr_source_map(value, generated);
                }
            }
            Stmt::Return(stmt) => {
                if let Some(value) = &stmt.value {
                    self.record_expr_source_map(value, generated);
                }
            }
            Stmt::With(stmt) => {
                self.source_map.push(RustSourceMapEntry {
                    kind: "with".to_string(),
                    source: stmt.span.clone(),
                    generated: generated.clone(),
                });
                self.record_expr_source_map(&stmt.resource, generated);
                self.record_block_source_map(&stmt.body, generated);
            }
            Stmt::If(stmt) => {
                self.record_expr_source_map(&stmt.condition, generated);
                self.record_block_source_map(&stmt.then_body, generated);
                if let Some(else_body) = &stmt.else_body {
                    self.record_block_source_map(else_body, generated);
                }
            }
            Stmt::Loop(stmt) => {
                if let Some(condition) = &stmt.condition {
                    self.record_expr_source_map(condition, generated);
                }
                self.record_block_source_map(&stmt.body, generated);
            }
            Stmt::For(stmt) => {
                self.record_expr_source_map(&stmt.iterable, generated);
                self.record_block_source_map(&stmt.body, generated);
            }
            Stmt::Match(stmt) => {
                self.record_expr_source_map(&stmt.value, generated);
                for arm in &stmt.arms {
                    self.record_block_source_map(&arm.body, generated);
                }
            }
            Stmt::LetElse(stmt) => {
                self.record_expr_source_map(&stmt.value, generated);
                self.record_block_source_map(&stmt.else_body, generated);
            }
            Stmt::Expr(expr) => self.record_expr_source_map(expr, generated),
            Stmt::Break(_)
            | Stmt::Continue(_)
            | Stmt::MalformedWith(_)
            | Stmt::MalformedIf(_)
            | Stmt::MalformedLoop(_)
            | Stmt::MalformedFor(_)
            | Stmt::MalformedMatch(_)
            | Stmt::Unknown(_) => {}
        }
    }

    fn record_block_source_map(&mut self, block: &Block, generated: &Span) {
        for statement in &block.statements {
            self.source_map.push(RustSourceMapEntry {
                kind: "statement".to_string(),
                source: stmt_span(statement).clone(),
                generated: generated.clone(),
            });
            self.record_statement_source_map(statement, generated);
        }
    }

    fn record_expr_source_map(&mut self, expr: &Expr, generated: &Span) {
        match expr {
            Expr::Binary { left, right, .. } => {
                self.record_expr_source_map(left, generated);
                self.record_expr_source_map(right, generated);
            }
            Expr::Field { base, span, .. } => {
                self.source_map.push(RustSourceMapEntry {
                    kind: "field_path".to_string(),
                    source: span.clone(),
                    generated: generated.clone(),
                });
                self.record_expr_source_map(base, generated);
            }
            Expr::Index { base, index, .. } => {
                self.record_expr_source_map(base, generated);
                self.record_expr_source_map(index, generated);
            }
            Expr::Call { callee, args, span } => {
                self.source_map.push(RustSourceMapEntry {
                    kind: "call".to_string(),
                    source: span.clone(),
                    generated: generated.clone(),
                });
                if self.is_native_boundary_call(callee) {
                    self.source_map.push(RustSourceMapEntry {
                        kind: "native_call".to_string(),
                        source: span.clone(),
                        generated: generated.clone(),
                    });
                }
                for arg in args {
                    self.source_map.push(RustSourceMapEntry {
                        kind: "named_arg".to_string(),
                        source: arg.span.clone(),
                        generated: generated.clone(),
                    });
                    self.record_expr_source_map(&arg.value, generated);
                }
            }
            Expr::Effect { value, .. } => self.record_expr_source_map(value, generated),
            Expr::Manage { value, span } => {
                self.source_map.push(RustSourceMapEntry {
                    kind: "manage".to_string(),
                    source: span.clone(),
                    generated: generated.clone(),
                });
                self.record_expr_source_map(value, generated);
            }
            Expr::Spawn { value, span } => {
                self.source_map.push(RustSourceMapEntry {
                    kind: "spawn".to_string(),
                    source: span.clone(),
                    generated: generated.clone(),
                });
                self.record_expr_source_map(value, generated);
            }
            Expr::Await { value, span } => {
                self.source_map.push(RustSourceMapEntry {
                    kind: "await".to_string(),
                    source: span.clone(),
                    generated: generated.clone(),
                });
                self.record_expr_source_map(value, generated);
            }
            Expr::Try { value, span } => {
                self.source_map.push(RustSourceMapEntry {
                    kind: "try".to_string(),
                    source: span.clone(),
                    generated: generated.clone(),
                });
                self.record_expr_source_map(value, generated);
            }
            Expr::Closure { body, .. } => self.record_block_source_map(body, generated),
            Expr::Ident(_, span) => self.source_map.push(RustSourceMapEntry {
                kind: "ident".to_string(),
                source: span.clone(),
                generated: generated.clone(),
            }),
            Expr::Number(_, span) => self.source_map.push(RustSourceMapEntry {
                kind: "number".to_string(),
                source: span.clone(),
                generated: generated.clone(),
            }),
            Expr::String(_, span) => self.source_map.push(RustSourceMapEntry {
                kind: "string".to_string(),
                source: span.clone(),
                generated: generated.clone(),
            }),
            Expr::Unknown(_) => {}
        }
    }

    fn is_native_boundary_call(&self, callee: &Callee) -> bool {
        let key = native_boundary_callee_key(callee);
        self.native_boundary_callees.contains(&key) || self.native_bindings.contains_key(&key)
    }

    fn await_call_lowers_to_pending(&self, callee: &Callee) -> bool {
        let key = native_boundary_callee_key(callee);
        is_async_runtime_intrinsic_callee(callee)
            || (self.async_native_boundary_callees.contains(&key)
                && self.native_bindings.contains_key(&key))
    }

    pub(super) fn lower_expr(&mut self, expr: &Expr) -> String {
        match expr {
            Expr::Ident(name, _) => {
                if self.drop_field_names.contains(name) {
                    format!("self.{}", rust_ident(name))
                } else if self.read_view_bindings.contains(name)
                    && self
                        .value_types
                        .get(name)
                        .is_some_and(|ty| !is_copy_type_ref(ty))
                {
                    format!("{}.clone()", rust_value_ident(name))
                } else if let Some(sum_name) = self.find_sum_type_for_variant(name) {
                    format!("{}::{}", rust_ident(&sum_name), rust_ident(name))
                } else {
                    lower_builtin_value_ident(name)
                        .map(str::to_string)
                        .unwrap_or_else(|| rust_value_ident(name))
                }
            }
            Expr::Number(value, _) => value.clone(),
            Expr::String(value, _) => format!("{:?}.to_string()", decode_string_token(value)),
            Expr::Binary {
                op, left, right, ..
            } => {
                let op = match op {
                    BinaryOp::Add => "+",
                    BinaryOp::Subtract => "-",
                    BinaryOp::Multiply => "*",
                    BinaryOp::Divide => "/",
                    BinaryOp::Equal => "==",
                    BinaryOp::NotEqual => "!=",
                    BinaryOp::Less => "<",
                    BinaryOp::LessEqual => "<=",
                    BinaryOp::Greater => ">",
                    BinaryOp::GreaterEqual => ">=",
                    BinaryOp::LogicalAnd => "&&",
                    BinaryOp::LogicalOr => "||",
                };
                if matches!(op, "==" | "!=")
                    && (self.is_string_comparison_operand(left)
                        || self.is_string_comparison_operand(right))
                {
                    return format!(
                        "{} {op} {}",
                        self.lower_string_comparison_operand(left),
                        self.lower_string_comparison_operand(right)
                    );
                }
                format!("{} {op} {}", self.lower_expr(left), self.lower_expr(right))
            }
            Expr::Field { base, name, span } => {
                if self
                    .infer_expr_type(base)
                    .is_some_and(|ty| self.is_class_type(&ty))
                {
                    format!(
                        "rsscript_runtime::unwrap_runtime({}.try_read_at({})).{}.clone()",
                        self.lower_expr(base),
                        lower_source_span(span),
                        rust_ident(name)
                    )
                } else if self.expr_is_read_view(base) {
                    let lowered = format!(
                        "{}.{}",
                        self.lower_read_view_base_expr(base),
                        rust_ident(name)
                    );
                    if self
                        .infer_expr_type(expr)
                        .is_some_and(|ty| !is_copy_type_ref(&ty))
                    {
                        format!("{lowered}.clone()")
                    } else {
                        lowered
                    }
                } else {
                    format!("{}.{}", self.lower_expr(base), rust_ident(name))
                }
            }
            Expr::Index { base, index, .. } => {
                format!("{}[{}]", self.lower_expr(base), self.lower_expr(index))
            }
            Expr::Call { callee, args, span } => {
                if let Callee::Name(name) = callee {
                    if let Some(type_kind) = self.type_kinds.get(name).copied() {
                        let mut fields = Vec::new();
                        for arg in args {
                            let field = arg
                                .name
                                .as_deref()
                                .map(rust_ident)
                                .unwrap_or_else(|| "/* unnamed */".to_string());
                            let is_weak_field = arg
                                .name
                                .as_deref()
                                .is_some_and(|field_name| self.is_weak_field(name, field_name));
                            if is_weak_field {
                                fields.push(format!(
                                    "{field}: {}",
                                    self.lower_explicit_weak_field_value(&arg.value)
                                ));
                            } else if arg.name.as_deref().is_some_and(|field_name| {
                                self.is_runtime_handle_field(name, field_name)
                            }) {
                                let field_name =
                                    arg.name.as_deref().unwrap_or_default().to_string();
                                fields.push(format!(
                                    "{field}: {}",
                                    self.lower_runtime_handle_field_value(
                                        name,
                                        &field_name,
                                        &arg.value,
                                        &arg.span
                                    )
                                ));
                            } else {
                                let value = self.lower_owned_expr(&arg.value);
                                fields.push(format!("{field}: {value}"));
                            }
                        }
                        let fields = fields.join(", ");
                        let constructed = format!("{} {{ {fields} }}", rust_ident(name));
                        if type_kind == TypeKind::Class {
                            return format!(
                                "rsscript_runtime::manage_at({constructed}, {})",
                                lower_source_span(span)
                            );
                        }
                        return constructed;
                    }

                    if is_rust_enum_constructor(name) {
                        let args = args
                            .iter()
                            .map(|arg| self.lower_expr(&arg.value))
                            .collect::<Vec<_>>()
                            .join(", ");
                        return format!("{}({args})", rust_ident(name));
                    }
                }
                if is_string_concat_callee(callee) {
                    return lower_string_concat_call(self, args);
                }
                if is_weak_upgrade_callee(callee) {
                    return lower_weak_upgrade_call(self, args);
                }
                if let Some(native_target) = self
                    .native_bindings
                    .get(&native_boundary_callee_key(callee))
                    .cloned()
                {
                    let args = args
                        .iter()
                        .map(|arg| self.lower_expr(&arg.value))
                        .collect::<Vec<_>>()
                        .join(", ");
                    return format!("{native_target}({args})");
                }
                if is_resource_pool_new_callee(callee) {
                    return lower_resource_pool_new_call(self, args, span);
                }
                if is_resource_pool_try_new_callee(callee) {
                    return lower_resource_pool_try_new_call(self, args, span);
                }
                if self.is_protocol_callee(callee) {
                    let lowered_callee = lower_protocol_callee(callee);
                    let args = args
                        .iter()
                        .enumerate()
                        .map(|(index, arg)| self.lower_call_arg_for_callee(callee, arg, index))
                        .collect::<Vec<_>>()
                        .join(", ");
                    return format!("{lowered_callee}({args})");
                }
                let is_resource_pool_borrow = is_resource_pool_borrow_callee(callee);
                let lowered_callee = if is_resource_pool_borrow {
                    "rsscript_runtime::ResourcePool::borrow_at".to_string()
                } else {
                    lower_callee(callee)
                };
                let mut args = args
                    .iter()
                    .enumerate()
                    .map(|(index, arg)| self.lower_call_arg_for_callee(callee, arg, index))
                    .collect::<Vec<_>>();
                if is_resource_pool_borrow {
                    args.push(lower_source_span(span));
                }
                let args = args.join(", ");
                format!("{lowered_callee}({args})")
            }
            Expr::Effect {
                effect,
                value,
                span,
            } => match effect {
                DataEffect::Read => {
                    if self.expr_is_read_view(value) {
                        self.lower_read_view_expr(value)
                    } else if self.expr_lowers_to_managed_non_class_handle(value) {
                        format!(
                            "&*rsscript_runtime::unwrap_runtime({}.try_read_at({}))",
                            self.lower_expr(value),
                            lower_source_span(span)
                        )
                    } else {
                        format!("&{}", self.lower_expr(value))
                    }
                }
                DataEffect::Mut => {
                    if let Expr::Ident(name, _) = &**value
                        && self.param_effects.get(name) == Some(&DataEffect::Mut)
                    {
                        rust_value_ident(name)
                    } else if self
                        .infer_expr_type(value)
                        .is_some_and(|ty| self.is_class_type(&ty))
                    {
                        format!("&{}", self.lower_expr(value))
                    } else if self.expr_lowers_to_managed_non_class_handle(value) {
                        format!(
                            "&mut *rsscript_runtime::unwrap_runtime({}.try_write_at({}))",
                            self.lower_expr(value),
                            lower_source_span(span)
                        )
                    } else {
                        format!("&mut {}", self.lower_expr(value))
                    }
                }
                DataEffect::Take => self.lower_expr(value),
            },
            Expr::Manage { value, span } => {
                format!(
                    "rsscript_runtime::manage_at({}, {})",
                    self.lower_expr(value),
                    lower_source_span(span)
                )
            }
            Expr::Spawn { span, .. } => unreachable_lowering("spawn expression", span),
            Expr::Await { value, .. } => self.lower_await_expr(value),
            Expr::Try { value, .. } => format!("{}?", self.lower_expr(value)),
            Expr::Closure { params, body, .. } => {
                let lowered_params = params
                    .iter()
                    .map(|param| rust_ident(param))
                    .collect::<Vec<_>>()
                    .join(", ");
                let previous_return_type = self.current_return_type.take();
                if let [Stmt::Expr(value)] = body.statements.as_slice() {
                    let lowered = format!("|{lowered_params}| {}", self.lower_expr(value));
                    self.current_return_type = previous_return_type;
                    return lowered;
                }
                let mut out = String::new();
                out.push_str(&format!("|{lowered_params}| {{\n"));
                self.lower_block(body, &mut out, 1);
                out.push('}');
                self.current_return_type = previous_return_type;
                out
            }
            Expr::Unknown(span) => unreachable_lowering("expression", span),
        }
    }

    fn lower_owned_expr(&mut self, expr: &Expr) -> String {
        match expr {
            Expr::Effect {
                effect: DataEffect::Read,
                value,
                span,
            }
            | Expr::Effect {
                effect: DataEffect::Mut,
                value,
                span,
            } => {
                if self.expr_lowers_to_managed_non_class_handle(value) {
                    format!(
                        "rsscript_runtime::unwrap_runtime({}.try_read_at({})).clone()",
                        self.lower_expr(value),
                        lower_source_span(span)
                    )
                } else {
                    format!("{}.clone()", self.lower_expr(value))
                }
            }
            Expr::Effect {
                effect: DataEffect::Take,
                value,
                ..
            } => self.lower_expr(value),
            _ => self.lower_expr(expr),
        }
    }

    fn lower_await_expr(&mut self, expr: &Expr) -> String {
        match expr {
            Expr::Try { value, .. } => format!("{}?", self.lower_await_expr(value)),
            Expr::Effect { value, .. } => self.lower_await_expr(value),
            Expr::Call { callee, .. } if self.await_call_lowers_to_pending(callee) => {
                let pending = self.lower_expr(expr);
                self.current_async_executor
                    .as_ref()
                    .map(|executor| format!("{executor}.run_pending({pending})"))
                    .unwrap_or_else(|| format!("rsscript_runtime::run_pending({pending})"))
            }
            Expr::Call { .. } => self.lower_expr(expr),
            _ => self.lower_expr(expr),
        }
    }

    fn expr_is_read_view(&self, expr: &Expr) -> bool {
        match expr {
            Expr::Ident(name, _) => self.read_view_bindings.contains(name),
            Expr::Field { base, .. } => self.expr_is_read_view(base),
            Expr::Effect { value, .. } | Expr::Try { value, .. } => self.expr_is_read_view(value),
            _ => false,
        }
    }

    fn lower_read_view_base_expr(&mut self, expr: &Expr) -> String {
        match expr {
            Expr::Ident(name, _) if self.read_view_bindings.contains(name) => {
                rust_value_ident(name)
            }
            _ => self.lower_expr(expr),
        }
    }

    fn lower_read_view_expr(&mut self, expr: &Expr) -> String {
        match expr {
            Expr::Ident(name, _) if self.read_view_bindings.contains(name) => {
                rust_value_ident(name)
            }
            Expr::Field { base, name, .. } if self.expr_is_read_view(base) => {
                format!(
                    "&{}.{}",
                    self.lower_read_view_base_expr(base),
                    rust_ident(name)
                )
            }
            _ => format!("&{}", self.lower_expr(expr)),
        }
    }

    fn lower_call_arg_for_callee(
        &mut self,
        callee: &Callee,
        arg: &CallArg,
        index: usize,
    ) -> String {
        if runtime_intrinsic_wants_managed_handle_arg(callee, arg.name.as_deref())
            && let Expr::Effect { effect, value, .. } = &arg.value
            && self.expr_lowers_to_managed_handle(value)
        {
            return match effect {
                DataEffect::Read => format!("&{}", self.lower_expr(value)),
                DataEffect::Mut => format!("&mut {}", self.lower_expr(value)),
                DataEffect::Take => self.lower_expr(value),
            };
        }
        if self.call_arg_is_retained(callee, arg, index)
            && runtime_intrinsic_target(callee).is_none()
            && let Expr::Effect { effect, value, .. } = &arg.value
            && self.expr_lowers_to_managed_handle(value)
        {
            return match effect {
                DataEffect::Read => format!("&{}", self.lower_expr(value)),
                DataEffect::Mut => format!("&mut {}", self.lower_expr(value)),
                DataEffect::Take => self.lower_expr(value),
            };
        }
        self.lower_expr(&arg.value)
    }

    fn call_arg_is_retained(&self, callee: &Callee, arg: &CallArg, _index: usize) -> bool {
        let Some(name) = arg.name.as_deref() else {
            return false;
        };
        self.retained_params_by_callee
            .get(&native_boundary_callee_key(callee))
            .is_some_and(|retained| retained.contains(name))
    }

    fn is_protocol_callee(&self, callee: &Callee) -> bool {
        matches!(callee, Callee::Qualified { namespace, .. } if self.protocol_names.contains(namespace))
    }

    fn lower_return_expr(&mut self, expr: &Expr) -> String {
        let lowered = self.lower_expr(expr);
        if self
            .current_return_type
            .as_ref()
            .is_some_and(is_result_type)
            && !is_result_constructor_expr(expr)
            && !self.expr_returns_result(expr)
        {
            format!("Ok({lowered})")
        } else {
            lowered
        }
    }

    fn expr_returns_result(&self, expr: &Expr) -> bool {
        match expr {
            Expr::Call { callee, .. } => {
                self.function_return_types
                    .get(&native_boundary_callee_key(callee))
                    .is_some_and(is_result_type)
                    || matches!(
                        callee,
                        Callee::Name(name)
                            if self
                                .value_types
                                .get(name)
                                .and_then(fn_type_return)
                                .is_some_and(is_result_type)
                    )
            }
            Expr::Effect { value, .. } | Expr::Manage { value, .. } => {
                self.expr_returns_result(value)
            }
            _ => false,
        }
    }

    fn infer_expr_type(&self, expr: &Expr) -> Option<TypeRef> {
        match expr {
            Expr::Ident(name, _) => self.value_types.get(name).cloned(),
            Expr::Field { base, name, span } => {
                let base_ty = self.infer_expr_type(base)?;
                self.field_type(&base_ty.name, name).map(|ty| TypeRef {
                    span: span.clone(),
                    ..ty
                })
            }
            Expr::Call {
                callee: Callee::Name(name),
                span,
                ..
            } if self.type_kinds.contains_key(name) => Some(TypeRef {
                name: name.clone(),
                args: Vec::new(),
                malformed_arg_spans: Vec::new(),
                is_fresh: false,
                is_noescape: false,
                fn_params: Vec::new(),
                fn_return: None,
                span: span.clone(),
            }),
            Expr::Call {
                callee: Callee::Name(name),
                ..
            } => self
                .value_types
                .get(name)
                .and_then(fn_type_return)
                .cloned()
                .or_else(|| {
                    self.function_return_types
                        .get(&native_boundary_callee_key(&Callee::Name(name.clone())))
                        .cloned()
                }),
            Expr::Call { callee, .. } => self
                .function_return_types
                .get(&native_boundary_callee_key(callee))
                .cloned(),
            Expr::Manage { value, .. } => self.infer_expr_type(value),
            Expr::Try { value, .. } => self
                .infer_expr_type(value)
                .and_then(|ty| result_ok_type_ref(&ty)),
            _ => None,
        }
    }

    fn expr_lowers_to_managed_handle(&self, expr: &Expr) -> bool {
        match expr {
            Expr::Ident(name, _) => self.managed_bindings.contains(name),
            Expr::Field { base, name, .. } => self
                .infer_expr_type(base)
                .is_some_and(|base_ty| self.is_runtime_handle_field(&base_ty.name, name)),
            Expr::Manage { .. } => true,
            Expr::Call {
                callee: Callee::Name(name),
                ..
            } => self
                .type_kinds
                .get(name)
                .is_some_and(|kind| *kind == TypeKind::Class),
            Expr::Effect { value, .. } | Expr::Try { value, .. } => {
                self.expr_lowers_to_managed_handle(value)
            }
            _ => false,
        }
    }

    fn expr_lowers_to_managed_non_class_handle(&self, expr: &Expr) -> bool {
        self.expr_lowers_to_managed_handle(expr)
            && !self
                .infer_expr_type(expr)
                .is_some_and(|ty| self.is_class_type(&ty))
    }

    fn is_string_comparison_operand(&self, expr: &Expr) -> bool {
        matches!(expr, Expr::String(_, _))
            || self
                .infer_expr_type(expr)
                .is_some_and(|ty| ty.name == "String" && ty.args.is_empty())
    }

    fn lower_string_comparison_operand(&mut self, expr: &Expr) -> String {
        match expr {
            Expr::String(value, _) => format!("{:?}", decode_string_token(value)),
            _ if self.is_string_comparison_operand(expr) => {
                format!("{}.as_str()", self.lower_expr(expr))
            }
            _ => self.lower_expr(expr),
        }
    }

    fn lower_type_ref(&self, ty: &TypeRef, position: ManagedPosition) -> String {
        if ty.name == "Fn" {
            let params = ty
                .fn_params
                .iter()
                .map(|param| self.lower_type_ref(param, ManagedPosition::Param))
                .collect::<Vec<_>>()
                .join(", ");
            let return_ty = ty.fn_return.as_ref().map(|return_ty| {
                format!(
                    " -> {}",
                    self.lower_type_ref(return_ty, ManagedPosition::Return)
                )
            });
            let return_ty = return_ty.unwrap_or_default();
            return match (ty.is_noescape, position) {
                (true, ManagedPosition::Param) => {
                    format!("impl FnMut({params}){return_ty}")
                }
                (true, _) => format!("Box<dyn FnMut({params}){return_ty}>"),
                (false, ManagedPosition::Param) => format!("dyn Fn({params}){return_ty}"),
                (false, _) => format!("Box<dyn Fn({params}){return_ty}>"),
            };
        }
        let lowered = match ty.name.as_str() {
            "Unit" => "()".to_string(),
            "Bool" => "bool".to_string(),
            "Byte" => "u8".to_string(),
            "Char" => "char".to_string(),
            "Int" => "i64".to_string(),
            "Int8" => "i8".to_string(),
            "Int16" => "i16".to_string(),
            "Int32" => "i32".to_string(),
            "Int64" => "i64".to_string(),
            "UInt" => "u64".to_string(),
            "UInt8" => "u8".to_string(),
            "UInt16" => "u16".to_string(),
            "UInt32" => "u32".to_string(),
            "UInt64" => "u64".to_string(),
            "Float" => "f64".to_string(),
            "Float32" => "f32".to_string(),
            "Float64" => "f64".to_string(),
            "String" => "String".to_string(),
            "StringBuilder" => "String".to_string(),
            "Url" => "String".to_string(),
            "Fd" => "i64".to_string(),
            "Bytes" | "Buffer" => "Vec<u8>".to_string(),
            "Path" => "std::path::PathBuf".to_string(),
            "Cache" if !self.type_kinds.contains_key("Cache") => {
                "rsscript_runtime::Cache".to_string()
            }
            "Rule" if !self.type_kinds.contains_key("Rule") => "rsscript_runtime::Rule".to_string(),
            "Config" if !self.type_kinds.contains_key("Config") => {
                "rsscript_runtime::Config".to_string()
            }
            "GlobalConfig" if !self.type_kinds.contains_key("GlobalConfig") => {
                "rsscript_runtime::GlobalConfig".to_string()
            }
            "Environment" => "rsscript_runtime::Environment".to_string(),
            "FunctionObject" => "rsscript_runtime::FunctionObject".to_string(),
            "Counter" => "rsscript_runtime::Counter".to_string(),
            "File" => "rsscript_runtime::File".to_string(),
            "FileError" | "IOError" => "std::io::Error".to_string(),
            "Request" => "rsscript_runtime::Request".to_string(),
            "Response" => "rsscript_runtime::Response".to_string(),
            "HttpError" => "rsscript_runtime::HttpError".to_string(),
            "TimerError" => "rsscript_runtime::TimerError".to_string(),
            "ConfigValue" => "rsscript_runtime::ConfigValue".to_string(),
            "ConfigStore" => "rsscript_runtime::ConfigStore".to_string(),
            "ConfigError" => "rsscript_runtime::ConfigError".to_string(),
            "DbConnection" => "rsscript_runtime::DbConnection".to_string(),
            "DbError" => "rsscript_runtime::DbError".to_string(),
            "Image" => "rsscript_runtime::Image".to_string(),
            "ImageCache" => "rsscript_runtime::ImageCache".to_string(),
            "ImageError" => "rsscript_runtime::ImageError".to_string(),
            "JsonValue" => "rsscript_runtime::JsonValue".to_string(),
            "JsonError" => "rsscript_runtime::JsonError".to_string(),
            "RowBuffer" => "rsscript_runtime::RowBuffer".to_string(),
            "Row" => "rsscript_runtime::Row".to_string(),
            "CsvError" => "rsscript_runtime::CsvError".to_string(),
            "Result" if ty.args.len() == 2 => format!(
                "Result<{}, {}>",
                self.lower_type_ref(&ty.args[0], ManagedPosition::Nested),
                self.lower_type_ref(&ty.args[1], ManagedPosition::Nested)
            ),
            "Option" if ty.args.len() == 1 => {
                format!(
                    "Option<{}>",
                    self.lower_type_ref(&ty.args[0], ManagedPosition::Nested)
                )
            }
            "List" if ty.args.len() == 1 => {
                format!(
                    "Vec<{}>",
                    self.lower_type_ref(&ty.args[0], ManagedPosition::Nested)
                )
            }
            "Map" if ty.args.len() == 2 => format!(
                "std::collections::HashMap<{}, {}>",
                self.lower_type_ref(&ty.args[0], ManagedPosition::Nested),
                self.lower_type_ref(&ty.args[1], ManagedPosition::Nested)
            ),
            "Set" if ty.args.len() == 1 => {
                format!(
                    "std::collections::HashSet<{}>",
                    self.lower_type_ref(&ty.args[0], ManagedPosition::Nested)
                )
            }
            "ResourcePool" if ty.args.len() == 1 => format!(
                "rsscript_runtime::ResourcePool<{}>",
                self.lower_type_ref(&ty.args[0], ManagedPosition::Nested)
            ),
            _ => {
                let name = rust_ident(&ty.name);
                if ty.args.is_empty() {
                    name
                } else {
                    format!(
                        "{}<{}>",
                        name,
                        ty.args
                            .iter()
                            .map(|arg| self.lower_type_ref(arg, ManagedPosition::Nested))
                            .collect::<Vec<_>>()
                            .join(", ")
                    )
                }
            }
        };

        if self.should_wrap_in_managed_handle(ty, position) {
            format!("rsscript_runtime::Managed<{lowered}>")
        } else {
            lowered
        }
    }

    fn should_wrap_in_managed_handle(&self, ty: &TypeRef, position: ManagedPosition) -> bool {
        if !matches!(
            position,
            ManagedPosition::Param | ManagedPosition::Return | ManagedPosition::Nested
        ) {
            return false;
        }
        matches!(self.type_kinds.get(&ty.name), Some(TypeKind::Class))
    }

    fn is_class_type(&self, ty: &TypeRef) -> bool {
        matches!(self.type_kinds.get(&ty.name), Some(TypeKind::Class))
    }

    fn is_weak_field(&self, type_name: &str, field_name: &str) -> bool {
        self.program.items.iter().any(|item| match item {
            Item::Type(ty) if ty.name == type_name => ty
                .fields
                .iter()
                .any(|field| field.name == field_name && field.is_weak),
            _ => false,
        })
    }

    fn is_runtime_handle_field(&self, type_name: &str, field_name: &str) -> bool {
        self.program.items.iter().any(|item| match item {
            Item::Type(ty) if ty.name == type_name => ty.fields.iter().any(|field| {
                field.name == field_name
                    && !field.is_weak
                    && (field.is_handle
                        || matches!(self.type_kinds.get(&field.ty.name), Some(TypeKind::Class)))
            }),
            _ => false,
        })
    }

    fn field_type(&self, type_name: &str, field_name: &str) -> Option<TypeRef> {
        self.program.items.iter().find_map(|item| match item {
            Item::Type(ty) if ty.name == type_name => ty
                .fields
                .iter()
                .find(|field| field.name == field_name)
                .map(|field| field.ty.clone()),
            _ => None,
        })
    }

    fn lower_runtime_handle_field_value(
        &mut self,
        type_name: &str,
        field_name: &str,
        expr: &Expr,
        span: &Span,
    ) -> String {
        let value = self.lower_owned_expr(expr);
        if self
            .field_type(type_name, field_name)
            .is_some_and(|ty| self.is_class_type(&ty))
        {
            value
        } else {
            format!(
                "rsscript_runtime::manage_at({value}, {})",
                lower_source_span(span)
            )
        }
    }

    fn lower_explicit_weak_field_value(&mut self, expr: &Expr) -> String {
        if let Some(value) = explicit_weak_handle_source(expr) {
            return self.lower_runtime_weak_from_managed(value);
        }
        self.lower_expr(expr)
    }

    fn lower_runtime_weak_from_managed(&mut self, expr: &Expr) -> String {
        if let Expr::Effect {
            effect: DataEffect::Read,
            value,
            ..
        } = expr
        {
            let value_expr = self.lower_expr(value);
            if let Expr::Ident(name, _) = &**value
                && matches!(
                    self.param_effects.get(name),
                    Some(DataEffect::Read | DataEffect::Mut)
                )
            {
                return format!("rsscript_runtime::weak({value_expr})");
            }
            return format!("rsscript_runtime::weak(&{value_expr})");
        }
        format!("rsscript_runtime::weak(&{})", self.lower_expr(expr))
    }

    fn find_sum_type_for_match(&self, arms: &[crate::syntax::ast::MatchArm]) -> Option<String> {
        // Check if any arm variant name matches a sum type's variant
        for arm in arms {
            if let MatchPattern::Variant { name, .. } = &arm.pattern {
                // Skip built-in Option/Result variants
                if matches!(name.as_str(), "Some" | "None" | "Ok" | "Err") {
                    return None;
                }
                // Find which sum type owns this variant
                for item in &self.program.items {
                    if let Item::SumType(sum) = item {
                        if sum.variants.iter().any(|v| v.name == *name) {
                            return Some(sum.name.clone());
                        }
                    }
                }
            }
        }
        None
    }

    fn find_sum_type_for_variant(&self, variant_name: &str) -> Option<String> {
        // Skip built-in variants
        if matches!(
            variant_name,
            "Some" | "None" | "Ok" | "Err" | "true" | "false"
        ) {
            return None;
        }
        for item in &self.program.items {
            if let Item::SumType(sum) = item {
                if sum.variants.iter().any(|v| v.name == variant_name) {
                    return Some(sum.name.clone());
                }
            }
        }
        None
    }
}

fn infer_const_type(expr: &Expr) -> String {
    match expr {
        Expr::Number(s, _) => {
            if s.contains('.') {
                "f64".to_string()
            } else {
                "i64".to_string()
            }
        }
        Expr::String(_, _) => "&'static str".to_string(),
        Expr::Ident(name, _) if name == "true" || name == "false" => "bool".to_string(),
        _ => "i64".to_string(), // fallback
    }
}

fn lower_const_value(expr: &Expr) -> String {
    match expr {
        Expr::Number(value, _) => value.clone(),
        Expr::String(value, _) => format!("\"{}\"", value.replace('\\', "\\\\").replace('"', "\\\"")),
        Expr::Ident(name, _) if name == "true" || name == "false" => name.clone(),
        _ => "()".to_string(), // unsupported const expression
    }
}
