// Generated by RSScript. Edit the .rss source instead.
// Runtime hooks are intentionally explicit while Rust lowering is stabilizing.
#![allow(dead_code, non_snake_case, non_camel_case_types, non_upper_case_globals, unused_parens)]
// RSScript features: <none>

// rss:span kind=type file=simple.rss line=1 column=1 length=6
#[derive(Debug, Clone)]
pub struct Point {
    pub x: i64,
    pub y: i64,
}

// rss:span kind=function file=simple.rss line=6 column=1 length=3
pub fn make_point(x: i64, y: i64) -> Point {
    // rss:span kind=statement file=simple.rss line=7 column=5 length=6
    return Point { x: x, y: y };
}
