[package]
name = "rss-async-runtime"
version = "0.1.0"
edition = "2026"

[sources]
paths = ["src"]

[implements."rss-async"]
version = "0.1"
interface_features = []
interface_effective_hash = "sha256:604a985dce961534bb724342ab11b981a3d304f8e55a175b0d9c3110d46f94a0"
