[package]
name = "rss-async-runtime"
version = "0.1.0"
edition = "2026"

[sources]
paths = ["src"]

[implements."rss-async"]
version = "0.1"
interface_features = []
interface_effective_hash = "sha256:f2723baf4534b3d3185cc2380b247ef04a03c51b05641af2ce9da79f35231019"
