[bindings]
"Sqlite.execute" = "rss_sqlite_native::execute"
"Sqlite.execute_params" = "rss_sqlite_native::execute_params"
"Sqlite.query_strings" = "rss_sqlite_native::query_strings"
"Sqlite.query_strings_params" = "rss_sqlite_native::query_strings_params"
"Sqlite.query_one_string" = "rss_sqlite_native::query_one_string"
"Sqlite.query_one_string_params" = "rss_sqlite_native::query_one_string_params"
