[package]
name = "structured-async-pipeline"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
rsscript_compiler = { package = "rsscript-sdk", path = "../../crates/rsscript-sdk", features = ["execution"] }
rsscript-abi-model = { path = "../../crates/rsscript-abi-model" }
rsscript-provider-api = { path = "../../crates/rsscript-provider-api" }

[build-dependencies]
rsscript-provider-bindgen = { path = "../../crates/rsscript-provider-bindgen" }
rsscript-semantics = { path = "../../crates/rsscript-semantics" }

[lints]
workspace = true
