// Standard package contracts that are prelude-visible only for single-file
// checks/lowering. Package review and package lowering must receive these
// through explicit package dependencies instead.
pub(crate) const STANDARD_PACKAGE_INTERFACES: &[(&str, &str)] = &[
    (
        "rss/async/interface/cancellation.rssi",
        include_str!("../rss/async/interface/cancellation.rssi"),
    ),
    (
        "rss/async/interface/channel.rssi",
        include_str!("../rss/async/interface/channel.rssi"),
    ),
    (
        "rss/async/interface/deadline.rssi",
        include_str!("../rss/async/interface/deadline.rssi"),
    ),
    (
        "rss/async/interface/file.rssi",
        include_str!("../rss/async/interface/file.rssi"),
    ),
    (
        "rss/async/interface/http.rssi",
        include_str!("../rss/async/interface/http.rssi"),
    ),
    (
        "rss/async/interface/process.rssi",
        include_str!("../rss/async/interface/process.rssi"),
    ),
    (
        "rss/async/interface/csv.rssi",
        include_str!("../rss/async/interface/csv.rssi"),
    ),
    (
        "rss/async/interface/stream.rssi",
        include_str!("../rss/async/interface/stream.rssi"),
    ),
    (
        "rss/async/interface/task.rssi",
        include_str!("../rss/async/interface/task.rssi"),
    ),
    (
        "rss/async/interface/tcp.rssi",
        include_str!("../rss/async/interface/tcp.rssi"),
    ),
    (
        "rss/async/interface/timer.rssi",
        include_str!("../rss/async/interface/timer.rssi"),
    ),
    (
        "rss/async/interface/websocket.rssi",
        include_str!("../rss/async/interface/websocket.rssi"),
    ),
];

pub(crate) const CORE_INTERFACES: &[(&str, &str)] = &[
    (
        "core/capability/capability.rssi",
        include_str!("../core/capability/capability.rssi"),
    ),
    (
        "core/cache/cache.rssi",
        include_str!("../core/cache/cache.rssi"),
    ),
    (
        "core/cache/image_cache.rssi",
        include_str!("../core/cache/image_cache.rssi"),
    ),
    (
        "core/clock/clock.rssi",
        include_str!("../core/clock/clock.rssi"),
    ),
    ("core/cmp/ord.rssi", include_str!("../core/cmp/ord.rssi")),
    (
        "core/collections/buffer.rssi",
        include_str!("../core/collections/buffer.rssi"),
    ),
    (
        "core/collections/bytes.rssi",
        include_str!("../core/collections/bytes.rssi"),
    ),
    (
        "core/collections/list.rssi",
        include_str!("../core/collections/list.rssi"),
    ),
    (
        "core/collections/map.rssi",
        include_str!("../core/collections/map.rssi"),
    ),
    (
        "core/collections/set.rssi",
        include_str!("../core/collections/set.rssi"),
    ),
    (
        "core/config/config.rssi",
        include_str!("../core/config/config.rssi"),
    ),
    (
        "core/config/rules.rssi",
        include_str!("../core/config/rules.rssi"),
    ),
    (
        "core/counter/counter.rssi",
        include_str!("../core/counter/counter.rssi"),
    ),
    ("core/csv/csv.rssi", include_str!("../core/csv/csv.rssi")),
    ("core/db/db.rssi", include_str!("../core/db/db.rssi")),
    (
        "core/diff/diff.rssi",
        include_str!("../core/diff/diff.rssi"),
    ),
    (
        "core/encoding/encoding.rssi",
        include_str!("../core/encoding/encoding.rssi"),
    ),
    ("core/env/env.rssi", include_str!("../core/env/env.rssi")),
    (
        "core/fs/directory.rssi",
        include_str!("../core/fs/directory.rssi"),
    ),
    ("core/fs/file.rssi", include_str!("../core/fs/file.rssi")),
    (
        "core/hash/hash.rssi",
        include_str!("../core/hash/hash.rssi"),
    ),
    (
        "core/http/client.rssi",
        include_str!("../core/http/client.rssi"),
    ),
    (
        "core/http/http.rssi",
        include_str!("../core/http/http.rssi"),
    ),
    (
        "core/interpreter/interpreter.rssi",
        include_str!("../core/interpreter/interpreter.rssi"),
    ),
    (
        "core/image/image.rssi",
        include_str!("../core/image/image.rssi"),
    ),
    (
        "core/json/json.rssi",
        include_str!("../core/json/json.rssi"),
    ),
    ("core/log/log.rssi", include_str!("../core/log/log.rssi")),
    (
        "core/option/option.rssi",
        include_str!("../core/option/option.rssi"),
    ),
    ("core/os/os.rssi", include_str!("../core/os/os.rssi")),
    (
        "core/path/path.rssi",
        include_str!("../core/path/path.rssi"),
    ),
    (
        "core/patch/patch.rssi",
        include_str!("../core/patch/patch.rssi"),
    ),
    (
        "core/process/process.rssi",
        include_str!("../core/process/process.rssi"),
    ),
    (
        "core/random/random.rssi",
        include_str!("../core/random/random.rssi"),
    ),
    (
        "core/regex/regex.rssi",
        include_str!("../core/regex/regex.rssi"),
    ),
    (
        "core/resource/resource_pool.rssi",
        include_str!("../core/resource/resource_pool.rssi"),
    ),
    (
        "core/result/result.rssi",
        include_str!("../core/result/result.rssi"),
    ),
    (
        "core/string/string.rssi",
        include_str!("../core/string/string.rssi"),
    ),
    (
        "core/tempdir/tempdir.rssi",
        include_str!("../core/tempdir/tempdir.rssi"),
    ),
    (
        "core/test/assert.rssi",
        include_str!("../core/test/assert.rssi"),
    ),
    (
        "core/toml/toml.rssi",
        include_str!("../core/toml/toml.rssi"),
    ),
    ("core/url/url.rssi", include_str!("../core/url/url.rssi")),
    (
        "core/weak/weak.rssi",
        include_str!("../core/weak/weak.rssi"),
    ),
    (
        "core/workspace/workspace.rssi",
        include_str!("../core/workspace/workspace.rssi"),
    ),
    (
        "core/yaml/yaml.rssi",
        include_str!("../core/yaml/yaml.rssi"),
    ),
];

pub(crate) fn builtin_interfaces() -> impl Iterator<Item = (&'static str, &'static str)> {
    CORE_INTERFACES.iter().copied()
}

pub(crate) fn default_interfaces() -> impl Iterator<Item = (&'static str, &'static str)> {
    CORE_INTERFACES
        .iter()
        .chain(STANDARD_PACKAGE_INTERFACES.iter())
        .copied()
}

pub(crate) fn standard_package_interfaces() -> impl Iterator<Item = (&'static str, &'static str)> {
    STANDARD_PACKAGE_INTERFACES.iter().copied()
}
