//! Deterministic language-reference material generated from owning registries.

use std::collections::BTreeMap;
use std::error::Error;
use std::fs;
use std::path::Path;

use rsscript_diagnostics::diagnostic_explanations;
use rsscript_interface_catalog::CORE_INTERFACES;
use rsscript_syntax::lexer::{BUILTIN_CONSTANTS, CONTEXTUAL_KEYWORDS, KEYWORDS};
use serde::Serialize;

const BEGIN: &str = "<!-- BEGIN GENERATED LANGUAGE CARD -->";
const END: &str = "<!-- END GENERATED LANGUAGE CARD -->";
const VERSION: u32 = 1;
const PARTIAL: &str = "partial";
const COMPLETE: &str = "complete";
const LANGUAGE_VERSION: &str = "0.7";
const SPEC_VERSION: &str = "RSScript_v0.7";

#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
struct Keyword {
    word: String,
    category: String,
    contextual: bool,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
struct CatalogDiagnostic {
    code: String,
    title: String,
    explanation: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
struct CoreInterface {
    path: String,
    sha256: String,
    source: String,
}

#[derive(Serialize)]
struct DiagnosticFixAvailability {
    scope: &'static str,
    available_from: [&'static str; 2],
    description: &'static str,
}

#[derive(Serialize)]
struct GrammarJson {
    schema: &'static str,
    version: u32,
    completeness: &'static str,
    provenance: [&'static str; 3],
    reserved_keywords: Vec<Keyword>,
    contextual_keywords: Vec<Keyword>,
    builtin_constants: Vec<String>,
}

#[derive(Serialize)]
struct DiagnosticCatalogJson {
    schema: &'static str,
    version: u32,
    completeness: &'static str,
    provenance: [&'static str; 1],
    fixes: DiagnosticFixAvailability,
    diagnostics: Vec<CatalogDiagnostic>,
}

#[derive(Serialize)]
struct CoreInterfacesJson {
    schema: &'static str,
    version: u32,
    completeness: &'static str,
    provenance: [&'static str; 1],
    sha256_algorithm: &'static str,
    interfaces: Vec<CoreInterface>,
}

#[derive(Serialize)]
struct LanguageCardJson {
    schema: &'static str,
    version: u32,
    completeness: &'static str,
    provenance: [&'static str; 3],
    language_version: &'static str,
    specification_version: &'static str,
    grammar_sha256_algorithm: &'static str,
    grammar_sha256: String,
    reserved_keyword_count: usize,
    contextual_keyword_count: usize,
    builtin_constant_count: usize,
    diagnostic_count: usize,
    core_interface_count: usize,
    diagnostic_fixes: DiagnosticFixAvailability,
    canonical_call_example: String,
}

pub fn run(root: &Path, check: bool) -> Result<(), Box<dyn Error>> {
    for (relative, contents) in generated_documents() {
        write_or_check(&root.join(relative), &contents, check)?;
    }
    let agent = root.join("AGENT.md");
    let existing = fs::read_to_string(&agent)?;
    let updated = update_machine_block(&existing, &agent_block());
    if check && existing != updated {
        return Err("AGENT.md generated language-card block is stale; run `cargo run -p rsscript-xtask -- language-card`".into());
    }
    if !check && existing != updated {
        fs::write(agent, updated)?;
    }
    println!(
        "language-card {}",
        if check { "is current" } else { "generated" }
    );
    Ok(())
}

fn generated_documents() -> BTreeMap<&'static str, String> {
    BTreeMap::from([
        ("docs/generated/grammar.md", grammar_document()),
        ("docs/generated/grammar.json", grammar_json()),
        ("docs/generated/keywords.md", keywords_document()),
        (
            "docs/generated/diagnostic-catalog.md",
            diagnostics_document(),
        ),
        ("docs/generated/diagnostic-catalog.json", diagnostics_json()),
        (
            "docs/generated/core-interfaces.md",
            core_interfaces_document(),
        ),
        (
            "docs/generated/core-interfaces.json",
            core_interfaces_json(),
        ),
        ("docs/generated/language-card.md", language_card_document()),
        ("docs/generated/language-card.json", language_card_json()),
    ])
}

fn header(title: &str, source: &str) -> String {
    format!(
        "<!-- generated by `cargo run -p rsscript-xtask -- language-card`; do not edit -->\n\n# {title}\n\nSource: `{source}`.\n\n"
    )
}

fn grammar_document() -> String {
    let keywords = keywords();
    let mut output = header("RSScript grammar surface", "rsscript-syntax lexer tables");
    output.push_str("This is a generated lexical reference, not a replacement for the parser. The parser and tests remain authoritative for production grammar and recovery. Its machine-readable companion is [grammar.json](grammar.json), marked `partial` because it does not claim a full EBNF.\n\n## Reserved keyword classes\n\n");
    for category in categories() {
        output.push_str(&format!("### {category}\n\n"));
        for keyword in &keywords {
            if !keyword.contextual && keyword.category == category {
                output.push_str(&format!("- `{}`\n", keyword.word));
            }
        }
        output.push('\n');
    }
    output.push_str("## Contextual words\n\n");
    for keyword in keywords.iter().filter(|keyword| keyword.contextual) {
        output.push_str(&format!("- `{}` ({})\n", keyword.word, keyword.category));
    }
    output.push_str("\n## Built-in constants and constructors\n\n");
    for constant in builtin_constants() {
        output.push_str(&format!("- `{constant}`\n"));
    }
    output
}

fn keywords_document() -> String {
    let mut output = header(
        "RSScript keyword classification",
        "rsscript-syntax::lexer::KEYWORDS",
    );
    output.push_str("Machine-readable lexical surface: [grammar.json](grammar.json).\n\n| Word | Classification | Reserved |\n| --- | --- | --- |\n");
    for keyword in keywords() {
        let reserved = if keyword.contextual {
            "contextual"
        } else {
            "yes"
        };
        output.push_str(&format!(
            "| `{}` | {} | {reserved} |\n",
            keyword.word, keyword.category
        ));
    }
    output
}

fn diagnostics_document() -> String {
    let mut output = header(
        "RSScript diagnostic catalog",
        "rsscript-diagnostics diagnostic registry",
    );
    output.push_str("Machine-readable catalog: [diagnostic-catalog.json](diagnostic-catalog.json). Static explanations do not invent fixes: machine-applicable edits are instance-level data returned by `rss check --json` or `rss fix --json`.\n\n| Code | Title | Explanation |\n| --- | --- | --- |\n");
    for diagnostic in diagnostics() {
        output.push_str(&format!(
            "| `{}` | {} | {} |\n",
            diagnostic.code,
            diagnostic.title,
            diagnostic.explanation.replace('|', "\\|")
        ));
    }
    output
}

fn core_interfaces_document() -> String {
    let interfaces = core_interfaces();
    let mut output = header(
        "RSScript core interfaces",
        "rsscript-interface-catalog::CORE_INTERFACES",
    );
    output.push_str(&format!("{} platform-neutral core interface files are available to the single-file environment. Machine-readable catalog: [core-interfaces.json](core-interfaces.json).\n\n", interfaces.len()));
    for interface in interfaces {
        output.push_str(&format!("- `{}`\n", interface.path));
    }
    output
}

fn language_card_document() -> String {
    let keyword_data = keywords();
    let mut output = header(
        "RSScript language card",
        "syntax, diagnostics, and core interface registries",
    );
    output.push_str("A compact generated index for contributors and tools.\n\n");
    output.push_str(&format!("- {} reserved keywords, {} contextual words, and {} built-in constants.\n- {} documented diagnostic codes.\n- {} platform-neutral core interface files.\n\n", keyword_data.iter().filter(|keyword| !keyword.contextual).count(), keyword_data.iter().filter(|keyword| keyword.contextual).count(), builtin_constants().len(), diagnostics().len(), core_interfaces().len()));
    output.push_str("- [Grammar surface](grammar.md) ([JSON](grammar.json))\n- [Keyword classification](keywords.md)\n- [Diagnostic catalog](diagnostic-catalog.md) ([JSON](diagnostic-catalog.json))\n- [Core interfaces](core-interfaces.md) ([JSON](core-interfaces.json))\n\nMachine-readable summary: [language-card.json](language-card.json). Diagnostic explanation catalogs do not fabricate fixes; machine-applicable edits are instance-level data returned by `rss check --json` and `rss fix --json`.\n\n## Canonical call spelling\n\nNamed arguments stay named. A direct call-site `read` wrapper is omitted because it is the default; `mut` and `take` remain explicit. The formatter does not invent or remove argument labels.\n\n```rsscript\n");
    output.push_str(&canonical_example());
    output.push_str("```\n");
    output
}

fn canonical_example() -> String {
    "fn apply(target: mut Buffer, input: take String, note: read String) -> Unit {}\n\nfn update(target: mut Buffer, input: take String, note: read String) -> Unit {\n    return apply(target: mut target, input: take input, note: note)\n}\n".to_string()
}

fn grammar_json() -> String {
    let all_keywords = keywords();
    json(&GrammarJson {
        schema: "rsscript.grammar.v1",
        version: VERSION,
        completeness: PARTIAL,
        provenance: [
            "rsscript_syntax::lexer::KEYWORDS",
            "rsscript_syntax::lexer::CONTEXTUAL_KEYWORDS",
            "rsscript_syntax::lexer::BUILTIN_CONSTANTS",
        ],
        reserved_keywords: all_keywords
            .iter()
            .filter(|keyword| !keyword.contextual)
            .cloned()
            .collect(),
        contextual_keywords: all_keywords
            .into_iter()
            .filter(|keyword| keyword.contextual)
            .collect(),
        builtin_constants: builtin_constants(),
    })
}

fn diagnostics_json() -> String {
    json(&DiagnosticCatalogJson {
        schema: "rsscript.diagnostic-catalog.v1",
        version: VERSION,
        completeness: COMPLETE,
        provenance: ["rsscript_diagnostics::diagnostic_explanations"],
        fixes: diagnostic_fix_availability(),
        diagnostics: diagnostics(),
    })
}

fn core_interfaces_json() -> String {
    json(&CoreInterfacesJson {
        schema: "rsscript.core-interfaces.v1",
        version: VERSION,
        completeness: COMPLETE,
        provenance: ["rsscript_interface_catalog::CORE_INTERFACES"],
        sha256_algorithm: "sha256",
        interfaces: core_interfaces(),
    })
}

fn language_card_json() -> String {
    let keyword_data = keywords();
    json(&LanguageCardJson {
        schema: "rsscript.language-card.v1",
        version: VERSION,
        completeness: PARTIAL,
        provenance: [
            "rsscript_syntax::lexer",
            "rsscript_diagnostics::diagnostic_explanations",
            "rsscript_interface_catalog::CORE_INTERFACES",
        ],
        language_version: LANGUAGE_VERSION,
        specification_version: SPEC_VERSION,
        grammar_sha256_algorithm: "sha256",
        grammar_sha256: grammar_sha256(),
        reserved_keyword_count: keyword_data
            .iter()
            .filter(|keyword| !keyword.contextual)
            .count(),
        contextual_keyword_count: keyword_data
            .iter()
            .filter(|keyword| keyword.contextual)
            .count(),
        builtin_constant_count: builtin_constants().len(),
        diagnostic_count: diagnostics().len(),
        core_interface_count: core_interfaces().len(),
        diagnostic_fixes: diagnostic_fix_availability(),
        canonical_call_example: canonical_example(),
    })
}

fn json(value: &impl Serialize) -> String {
    let mut output = serde_json::to_string_pretty(value).expect("generated JSON is serializable");
    output.push('\n');
    output
}

fn grammar_sha256() -> String {
    sha256(&grammar_json())
}

fn sha256(source: &str) -> String {
    use sha2::{Digest, Sha256};

    let digest = Sha256::digest(source.as_bytes());
    format!("{digest:x}")
}

fn diagnostic_fix_availability() -> DiagnosticFixAvailability {
    DiagnosticFixAvailability {
        scope: "instance_only",
        available_from: ["rss check --json", "rss fix --json"],
        description: "Static diagnostic explanations do not claim fixes; machine-applicable edits are attached to concrete diagnostic instances.",
    }
}

fn categories() -> [&'static str; 4] {
    ["control", "declaration", "modifier", "ownership"]
}

fn keywords() -> Vec<Keyword> {
    let mut output = KEYWORDS
        .iter()
        .map(|(word, category)| Keyword {
            word: (*word).to_string(),
            category: format!("{category:?}").to_ascii_lowercase(),
            contextual: false,
        })
        .collect::<Vec<_>>();
    output.extend(CONTEXTUAL_KEYWORDS.iter().map(|(word, category)| Keyword {
        word: (*word).to_string(),
        category: format!("{category:?}").to_ascii_lowercase(),
        contextual: true,
    }));
    output.sort_by(|left, right| left.word.cmp(&right.word));
    output
}

fn builtin_constants() -> Vec<String> {
    let mut constants = BUILTIN_CONSTANTS
        .iter()
        .map(|constant| (*constant).to_string())
        .collect::<Vec<_>>();
    constants.sort();
    constants
}

fn diagnostics() -> Vec<CatalogDiagnostic> {
    let mut catalog = diagnostic_explanations()
        .iter()
        .map(|diagnostic| CatalogDiagnostic {
            code: diagnostic.code.to_string(),
            title: diagnostic.title.to_string(),
            explanation: diagnostic.explanation.to_string(),
        })
        .collect::<Vec<_>>();
    catalog.sort_by(|left, right| left.code.cmp(&right.code));
    catalog
}

fn core_interfaces() -> Vec<CoreInterface> {
    let mut interfaces = CORE_INTERFACES
        .iter()
        .map(|(path, source)| CoreInterface {
            path: (*path).to_string(),
            sha256: sha256(source),
            source: (*source).to_string(),
        })
        .collect::<Vec<_>>();
    interfaces.sort_by(|left, right| left.path.cmp(&right.path));
    interfaces
}

fn agent_block() -> String {
    format!(
        "{BEGIN}\n\n## Generated language card\n\nThe generated [language card](docs/generated/language-card.md) and machine-readable [language card](docs/generated/language-card.json), [grammar](docs/generated/grammar.json), [diagnostic catalog](docs/generated/diagnostic-catalog.json), and [core-interface catalog](docs/generated/core-interfaces.json) are derived from syntax keyword tables, the diagnostic registry, and the core-interface catalog. Refresh them with `cargo run -p rsscript-xtask -- language-card`; verify freshness with the same command plus `--check`.\n\n{END}"
    )
}

fn update_machine_block(document: &str, block: &str) -> String {
    match (document.find(BEGIN), document.find(END)) {
        (Some(start), Some(end)) if start < end => format!(
            "{}{}{}",
            &document[..start],
            block,
            &document[end + END.len()..]
        ),
        _ => format!("{}\n\n{}\n", document.trim_end(), block),
    }
}

fn write_or_check(path: &Path, contents: &str, check: bool) -> Result<(), Box<dyn Error>> {
    if check {
        if fs::read_to_string(path).unwrap_or_default() != contents {
            return Err(format!(
                "{} is stale; run `cargo run -p rsscript-xtask -- language-card`",
                path.display()
            )
            .into());
        }
    } else {
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent)?;
        }
        if fs::read_to_string(path).ok().as_deref() != Some(contents) {
            fs::write(path, contents)?;
        }
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn machine_block_is_replaced_without_touching_surrounding_text() {
        let input = format!("before\n{BEGIN}\nold\n{END}\nafter\n");
        assert_eq!(update_machine_block(&input, "new"), "before\nnew\nafter\n");
    }

    #[test]
    fn registry_sources_produce_the_canonical_card() {
        assert!(keywords().iter().any(|keyword| keyword.word == "take"));
        assert!(
            diagnostics()
                .iter()
                .any(|diagnostic| diagnostic.code == "RS0202")
        );
        assert!(
            core_interfaces()
                .iter()
                .any(|interface| interface.path.ends_with("string.rssi"))
        );
        assert!(canonical_example().contains("note: note"));
    }

    #[test]
    fn machine_readable_catalogs_have_stable_provenance_and_declared_scope() {
        let grammar: serde_json::Value = serde_json::from_str(&grammar_json()).unwrap();
        assert_eq!(grammar["schema"], "rsscript.grammar.v1");
        assert_eq!(grammar["version"], VERSION);
        assert_eq!(grammar["completeness"], PARTIAL);
        assert!(grammar["reserved_keywords"].is_array());

        let diagnostics: serde_json::Value = serde_json::from_str(&diagnostics_json()).unwrap();
        assert_eq!(
            diagnostics["provenance"][0],
            "rsscript_diagnostics::diagnostic_explanations"
        );
        assert_eq!(diagnostics["completeness"], COMPLETE);
        assert_eq!(diagnostics["fixes"]["scope"], "instance_only");
        assert_eq!(
            diagnostics["fixes"]["available_from"][0],
            "rss check --json"
        );
        let diagnostic_codes = diagnostics["diagnostics"]
            .as_array()
            .expect("diagnostics array")
            .iter()
            .map(|diagnostic| diagnostic["code"].as_str().expect("diagnostic code"))
            .collect::<Vec<_>>();
        assert!(diagnostic_codes.windows(2).all(|pair| pair[0] <= pair[1]));

        let interfaces: serde_json::Value = serde_json::from_str(&core_interfaces_json()).unwrap();
        assert_eq!(interfaces["completeness"], COMPLETE);
        assert_eq!(interfaces["sha256_algorithm"], "sha256");
        let interface_paths = interfaces["interfaces"]
            .as_array()
            .expect("interfaces array")
            .iter()
            .map(|interface| interface["path"].as_str().expect("interface path"))
            .collect::<Vec<_>>();
        assert!(interface_paths.windows(2).all(|pair| pair[0] <= pair[1]));
        let string = interfaces["interfaces"]
            .as_array()
            .and_then(|catalog| {
                catalog
                    .iter()
                    .find(|interface| interface["path"] == "stdlib/string/string.rssi")
            })
            .expect("string interface");
        let source = string["source"].as_str().expect("string source");
        assert!(source.contains("pub fn String.concat"));
        assert_eq!(string["sha256"], sha256(source));

        let card: serde_json::Value = serde_json::from_str(&language_card_json()).unwrap();
        assert_eq!(card["schema"], "rsscript.language-card.v1");
        assert_eq!(card["language_version"], LANGUAGE_VERSION);
        assert_eq!(card["specification_version"], SPEC_VERSION);
        assert_eq!(card["grammar_sha256_algorithm"], "sha256");
        assert_eq!(card["grammar_sha256"], grammar_sha256());
        assert_eq!(card["diagnostic_fixes"]["scope"], "instance_only");
        assert!(
            card["canonical_call_example"]
                .as_str()
                .is_some_and(|example| example.contains("note: note"))
        );
    }

    #[test]
    fn canonical_example_is_semantically_valid() {
        let diagnostics =
            rsscript_semantics::analyze_source("language-card.rss", &canonical_example());
        assert!(
            diagnostics
                .iter()
                .all(|diagnostic| !diagnostic.severity.is_error()),
            "canonical language-card example must be valid: {diagnostics:#?}"
        );
    }
}
