[package]
name = "rsscript-provider-fs"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
rsscript-abi-model = { path = "../../crates/rsscript-abi-model" }
rsscript-provider-api = { path = "../../crates/rsscript-provider-api" }

[target.'cfg(unix)'.dependencies]
rustix = { version = "1.1", features = ["fs"] }

[build-dependencies]
rsscript-provider-bindgen = { path = "../../crates/rsscript-provider-bindgen" }
rsscript-semantics = { path = "../../crates/rsscript-semantics" }

[dev-dependencies]
rsscript-provider-conformance = { path = "../../crates/rsscript-provider-conformance" }

[lints]
workspace = true
