[package]
name = "rss-async-runtime"
version = "0.1.0"
edition = "2026"

[sources]
paths = ["src"]

[implements."rss-async"]
version = "0.1"
interface_features = []
interface_effective_hash = "sha256:af950044537870ee454b4541da58c1bc27ea48f73fa17a4271eb5ed30b272997"
