[package]
name = "rss-async-runtime"
version = "0.1.0"
edition = "2026"

[sources]
paths = ["src"]

[implements."rss-async"]
version = "0.1"
interface_features = []
interface_effective_hash = "sha256:3b8cb6475d2dc480c4c0372183e1f6810521377170a00b2269e5d7a3d8a6969c"
